### ISSUE TITLE
Provide component links in js/ts files

### ISSUE THREAD

**Issue by Ilanaya** [zardoy/vetur-extended#13]
Realized that I'm missing the same feature in ts/js files. Can we support `javascript` and `typescript` languages, or shouldn't they be included in the vue-specific extension?
I think this is pretty easy - just need to add langs ids [there](https://github.com/zardoy/vetur-extended/blob/5d21ceaa422ec107ee90b6ae8244a0db33f52d59/src/componentsLinks.ts#L15)

WDYT?

**Comment by zardoy** [comment]
Performance cost of this feature is high, so you can do it but behind the boolean setting.
