### ISSUE TITLE
Add support for absolute paths from project root

### ISSUE THREAD

**Issue by nolimitdev** [zardoy/vetur-extended#23]
When using absolute paths from project root like `import MyComp from '/src/components/my-comp.vue'`  [vetur-extended](https://github.com/zardoy/vetur-extended) does not make path clickable but project is compiled OK - webpack recognizes this path.

**Comment by zardoy** [comment]
did you try configuring `paths` (aliases) in tsconfig of your project?

**Comment by nolimitdev** [comment]
I have `paths`in jsconfig and vscode correcly recognizes import paths in *.js files but this does not work for *.vue files. Do I need tsconfig for this plugin?

**Comment by nolimitdev** [comment]
using tsconfig did not fix this issue. In jsconfig I have 

    "compilerOptions": {
        "baseUrl": "./",
        "paths": {
            "*": ["./*"]
        }
    },

and vscode recognizes absolute imports thanks to it

**Comment by zardoy** [comment]
do you the latest version of volar / vue plugin?
